### ISSUE TITLE
[ISSUE] - FilesAPI throws NPE when file is not found

### ISSUE THREAD

**Issue by costichiulan** [databricks/databricks-sdk-java#259]
**Description**
I'm trying to use `getMetadata` method of FilesAPI client, but if file is not found, a Null Pointer Exception is thrown.

**Reproduction**
new WorkspaceClient(config).files().getMetadata("/Volumes/main/default/file-not-found")

**Expected behavior**
When file is not found ( 404 error received from Databricks API) , a Databricks Error with errorCode = "NOT_FOUND" or error code = "RESOURCE_DOES_NOT_EXIST" should be thrown.

**Is it a regression?**
No

**Debug Logs**
java.lang.NullPointerException: null
	at java.base/java.io.Reader.<init>(Reader.java:168)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:112)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1152)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:3105)
	at com.databricks.sdk.core.error.ApiErrors.parseApiError(ApiErrors.java:70)
	at com.databricks.sdk.core.error.ApiErrors.readErrorFromResponse(ApiErrors.java:34)
	at com.databricks.sdk.core.error.ApiErrors.checkForRetry(ApiErrors.java:26)
	at com.databricks.sdk.core.ApiClient.executeInner(ApiClient.java:258)
	at com.databricks.sdk.core.ApiClient.getResponse(ApiClient.java:219)
	at com.databricks.sdk.core.ApiClient.execute(ApiClient.java:210)
	at com.databricks.sdk.core.ApiClient.HEAD(ApiClient.java:127)
	at com.databricks.sdk.service.files.FilesImpl.getMetadata(FilesImpl.java:74)
	at com.databricks.sdk.service.files.FilesAPI.getMetadata(FilesAPI.java:133)
	at com.databricks.sdk.service.files.FilesAPI.getMetadata(FilesAPI.java:123)

**Other Information**
 - OS: macOS
 - Version: 0.22.0

**Comment by rohit-satya** [comment]
@costichiulan Please assign this issue to me
