### ISSUE TITLE
Unparsable Request Exception when Patching Group

### ISSUE THREAD

**Issue by fernanluyano** [databricks/databricks-sdk-java#279]
**Description**
Getting "invalidSyntax Request is unparsable, syntactically incorrect, or violates schema" when patching an account group.

**Reproduction**
Using Kotlin in this case.
`client` is a valid `AccountClient` I use often.
`member` and `group` are `Group` objects (SDK `iam` package) I previously obtained with the SDK. The goal is to patch `group` by adding `member` as a member of `group`. I can do it directly with the Databricks API in a REST call.

```
val patch = Patch().setOp(PatchOp.ADD).setPath("members").setValue(member.id)
val req = PartialUpdate()
            .setSchemas(listOf(PatchSchema.URN_IETF_PARAMS_SCIM_API_MESSAGES_2_0_PATCH_OP))
            .setOperations(listOf(patch))
            .setId(group.id)
 client.groups().patch(req)
```

**Expected behavior**
Patch the account group successfully.

**Debug Logs**
invalidSyntax Request is unparsable, syntactically incorrect, or violates schema.
com.databricks.sdk.core.error.platform.BadRequest: invalidSyntax Request is unparsable, syntactically incorrect, or violates schema.
	at com.databricks.sdk.core.error.AbstractErrorMapper.apply(AbstractErrorMapper.java:43)
	at com.databricks.sdk.core.error.ApiErrors.readErrorFromResponse(ApiErrors.java:55)
	at com.databricks.sdk.core.error.ApiErrors.getDatabricksError(ApiErrors.java:27)
	at com.databricks.sdk.core.ApiClient.executeInner(ApiClient.java:275)
	at com.databricks.sdk.core.ApiClient.getResponse(ApiClient.java:235)
	at com.databricks.sdk.core.ApiClient.execute(ApiClient.java:226)
	at com.databricks.sdk.core.ApiClient.PATCH(ApiClient.java:179)
	at com.databricks.sdk.service.iam.AccountGroupsImpl.patch(AccountGroupsImpl.java:67)
	at com.databricks.sdk.service.iam.AccountGroupsAPI.patch(AccountGroupsAPI.java:105)

**Other Information**
 - OS: macOS
 - https://docs.databricks.com/api/workspace/groups/patch

**Comment by mgyucht** [comment]
Yeah, unfortunately the SCIM Patch API is a bit cumbersome to use.

When patching, you need to set the "value" to a list of `ComplexValue` and set the `value` field to the user ID. See https://github.com/databricks/databricks-sdk-py/blob/main/examples/groups/patch_groups.py for the equivalent request in the Python SDK.

**Comment by fernanluyano** [comment]
Thank you for the feedback

**Comment by fernanluyano** [comment]
Solved, it was a bad call due to the complexity of the SCIM API
